In [1]:
import pandas as pd

In [2]:
# disney_movies_df = pd.read_csv("./data/disney_movies_total_gross.csv")

In [3]:
# disney_movies_df.info()

In [4]:
# disney_movies_df

In [5]:
disney_plus_shows_df = pd.read_csv("./data/disney_plus_shows.csv")
disney_plus_shows_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      894 non-null    object
 1   title        894 non-null    object
 2   plot         866 non-null    object
 3   type         894 non-null    object
 4   rated        742 non-null    object
 5   year         894 non-null    object
 6   released_at  874 non-null    object
 7   added_at     992 non-null    object
 8   runtime      838 non-null    object
 9   genre        885 non-null    object
 10  director     689 non-null    object
 11  writer       743 non-null    object
 12  actors       870 non-null    object
 13  language     865 non-null    object
 14  country      869 non-null    object
 15  awards       556 non-null    object
 16  metascore    292 non-null    float64
 17  imdb_rating  879 non-null    float64
 18  imdb_votes   879 non-null    object
dtypes: float64(2), object(17)
memory usage: 147.4+ KB

In [6]:
disney_plus_shows_df

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434"
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,tt3544734,Zapped,"When Zoey's mom remarries, Zoey finds it hard ...",movie,TV-G,2014,23 Jun 2014,"November 12, 2019",102 min,"Comedy, Family, Fantasy",Peter DeLuise,"Leslie Margolis (based on the novel ""Boys Are ...","Zendaya, Chanelle Peloso, Spencer Boldman, Emi...",English,"Canada, USA",5 wins & 1 nomination.,NaN,5.1,"3,750"
988,tt0186726,Zenon: Girl of the 21st Century,An inquisitive teenager pries into suspected d...,movie,TV-G,1999,23 Jan 1999,"November 12, 2019",97 min,"Adventure, Comedy, Family, Sci-Fi",Kenneth Johnson,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Raven-Symoné, Stuart Pankin, H...",English,USA,2 nominations.,NaN,6.4,"6,378"
989,tt0271271,Zenon: The Zequel,A mischievous fifteen-year-old girl living on ...,movie,TV-G,2001,12 Jan 2001,"November 12, 2019",100 min,"Comedy, Family, Adventure, Sci-Fi",Manny Coto,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Shadia Simmons, Lauren Maltby,...",English,"USA, New Zealand",1 nomination.,NaN,5.9,"3,318"
990,tt0379060,Zenon: Z3,The heroine sets out to win an important compe...,movie,TV-G,2004,11 Jun 2004,"November 12, 2019",81 min,"Adventure, Comedy, Family, Sci-Fi",Steve Rash,"Marilyn Sadler (character from the book ""Zenon...","Kirsten Storms, Lauren Maltby, Alyson Morgan, ...",English,USA,NaN,NaN,5.5,"2,339"
991,tt2948356,Zootopia,"In a city of anthropomorphic animals, a rookie...",movie,PG,2016,04 Mar 2016,"November 12, 2019",108 min,"Animation, Adventure, Comedy, Crime, Family, M...","Byron Howard, Rich Moore, Jared Bush(co-director)","Byron Howard (story by), Rich Moore (story by)...","Ginnifer Goodwin, Jason Bateman, Idris Elba, J...",English,USA,Won 1 Oscar. Another 46 wins & 71 nominations.,78.0,8.0,"410,437"

In [7]:
disney_plus_shows_df.columns

Index(['imdb_id', 'title', 'plot', 'type', 'rated', 'year', 'released_at',
       'added_at', 'runtime', 'genre', 'director', 'writer', 'actors',
       'language', 'country', 'awards', 'metascore', 'imdb_rating',
       'imdb_votes'],
      dtype='object')

In [8]:
# Removing unwanted columns
disney_plus_shows_df.drop(columns=['imdb_id','title','plot','rated','released_at','added_at','genre', 'director', 'writer', 'actors','language', 'country', 'awards', 'metascore','imdb_votes'], inplace=True)
disney_plus_shows_df

       type   year  runtime  imdb_rating
0     movie   1999   97 min          7.3
1    series  2018–      NaN          6.2
2     movie   1996  103 min          5.7
3     movie   2002   74 min          5.8
4     movie   2000  100 min          4.9
..      ...    ...      ...          ...
987   movie   2014  102 min          5.1
988   movie   1999   97 min          6.4
989   movie   2001  100 min          5.9
990   movie   2004   81 min          5.5
991   movie   2016  108 min          8.0

[992 rows x 4 columns]

In [9]:
disney_plus_shows_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   type         894 non-null    object
 1   year         894 non-null    object
 2   runtime      838 non-null    object
 3   imdb_rating  879 non-null    float64
dtypes: float64(1), object(3)
memory usage: 31.1+ KB

In [10]:
# Dropping nan values from the dataframe

disney_plus_shows_df.dropna(axis='rows', how='any', inplace=True)
disney_plus_shows_df

      type  year  runtime  imdb_rating
0    movie  1999   97 min          7.3
2    movie  1996  103 min          5.7
3    movie  2002   74 min          5.8
4    movie  2000  100 min          4.9
5    movie  2011   90 min          6.3
..     ...   ...      ...          ...
987  movie  2014  102 min          5.1
988  movie  1999   97 min          6.4
989  movie  2001  100 min          5.9
990  movie  2004   81 min          5.5
991  movie  2016  108 min          8.0

[831 rows x 4 columns]

In [11]:
# Identify the target variable as metascore
y = disney_plus_shows_df['imdb_rating']
y

0      7.3
2      5.7
3      5.8
4      4.9
5      6.3
      ...
987    5.1
988    6.4
989    5.9
990    5.5
991    8.0
Name: imdb_rating, Length: 831, dtype: float64

In [12]:
X = disney_plus_shows_df.drop(columns=['imdb_rating'])
X

      type  year  runtime
0    movie  1999   97 min
2    movie  1996  103 min
3    movie  2002   74 min
4    movie  2000  100 min
5    movie  2011   90 min
..     ...   ...      ...
987  movie  2014  102 min
988  movie  1999   97 min
989  movie  2001  100 min
990  movie  2004   81 min
991  movie  2016  108 min

[831 rows x 3 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [15]:
# simple regression
from sklearn.linear_model import LinearRegression

In [19]:
model = LinearRegression()

In [21]:
# Fitting our model with all of our features in X
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'series'

In [22]:
# predict y
y_predict = model.predict(X_test)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
# access the model
score = model.score(y_test, prediction)